
HOSTNAME = '127.0.0.1'
PORT     = '3306'
DATABASE = 'flask_project'
USERNAME = 'root'
PASSWORD = 'root'
DB_URI = 'mysql+pymysql://{}:{}@{}:{}/{}'.format(USERNAME,PASSWORD,HOSTNAME,PORT,DATABASE)
SQLALCHEMY_DATABASE_URI=DB_URI
SQLALCHEMY_TRACK_MODIFICATIONS=True

SECRET_KEY="1208993u219hjid109"

#flask-email
MAIL_SERVER = "smtp.qq.com"
MAIL_PORT = 465
MAIL_USE_TLS = False
MAIL_USE_SSL = True
MAIL_DEBUG = True
MAIL_USERNAME = "1151967706@qq.com"
MAIL_PASSWORD = "pxzukpayvtejfief"
MAIL_DEFAULT_SENDER = "1151967706@qq.com"